name: surplus
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  firebase_core: ^2.21.0
  equatable: ^2.0.5
  firebase_messaging: ^14.7.3
  dio: ^5.3.3
  device_info_plus: ^9.1.0
  socket_io_client: ^2.0.3+1
  flutter_bloc: ^8.1.3
  geolocator: ^10.1.0
  internet_connectivity_checker: ^1.0.2
  google_fonts: ^6.1.0
  file_picker: ^6.0.0
  flutter_local_notifications: ^16.1.0
  path_provider: ^2.1.1
  go_router: ^12.1.1
  bloc: ^8.1.2
  hydrated_bloc: ^9.1.2
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  path: ^1.8.3
  rxdart: ^0.27.7
  share_plus: ^7.2.1
  url_launcher: ^6.2.1
  flutter_linkify: ^6.0.0
  flutter_native_splash: ^2.3.6
  connectivity_plus: ^5.0.2
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/s.jpg"

flutter:
  uses-material-design: true

  assets:
   - assets/svgs/
   - assets/lotties/
   - assets/images/
